site_name: 《机器人系统》课程
site_url: https://robotic.uwis.cn
copyright: 成都信息工程大学 软件工程学院
nav:
  - 课程简介: index.md
  - 教学大纲: syllabus.md
  - 教师简介: instructor.md
  - 课程内容:
      - 第1章 机器人基础: chapter1.md
      - 第2章 CubeMX编程指南: chapter2.md
      - 第3章 PicSimlab仿真开发: chapter3.md
      - 第4章 嵌入式软件设计模式: chapter4.md
      - 第5章 Renode 高级仿真编程: chapter5.md
      - 第6章 嵌入式实时操作系统（FreeRTOS）: chapter6.md
      - 第7章 STM32 定时器的应用: chapter7.md
      - 第8章 PWM 波与电机驱动: chapter8.md
      - 第9章 闭环控制与 PID: chapter9.md
      - 第10章 嵌入式系统与互联网: chapter10.md
      - 第11章 课程工程实践项目: chapter11.md
      - 第12章 嵌入式开发环境配置: chapter12.md
  - 参考资料: resources.md
theme:
  name: material
  features:
    - navigation.expand

extra_css:
  - assets/stylesheets/exam-login.css

extra_javascript:
  - assets/javascripts/exam-login.js
  - assets/javascripts/footer-links.js
  - assets/javascripts/lib/mermaid.min.js
  - assets/javascripts/mermaid-init.js

plugins:
  - search:
      lang:
        - zh
        - en
  - mkdocs_quiz

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.superfences
  - plantuml_markdown:
      server: https://www.plantuml.com/plantuml
      format: png
    # - markdown_svgbob:
    #     tag_type: inline_svg
    #     bg_color: white
    #     fg_color: black
    #     min_char_width: 80
