site_name: 《机器人系统》课程
site_url: http://robotic.uwis.cn
copyright: 成都信息工程大学 软件工程学院
nav:
  - 首页: index.md
  - 教师简介: instructor.md
  - 课程介绍: intro.md
  - 教学大纲: syllabus.md
  - 参考资料: resources.md
theme:
  name: material
  features:
    - navigation.expand

plugins:
  - search:
      lang:
        - zh
        - en

markdown_extensions:
  - plantuml_markdown:
      server: https://www.plantuml.com/plantuml
      format: png
