[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:xvnc]
command=/usr/bin/Xtigervnc :1 -geometry %(ENV_VNC_RESOLUTION)s -depth 24 -rfbport %(ENV_VNC_PORT)s -rfbauth /home/picsimlab/.vnc/passwd -SecurityTypes VncAuth -localhost no
user=picsimlab
autorestart=true
priority=10

[program:openbox]
command=/usr/bin/openbox-session
user=picsimlab
environment=DISPLAY=":1",HOME="/home/picsimlab"
autorestart=true
priority=20

[program:novnc]
command=/usr/bin/websockify --web /usr/share/novnc %(ENV_NOVNC_PORT)s localhost:%(ENV_VNC_PORT)s
user=picsimlab
autorestart=true
priority=30
